### ISSUE TITLE
Credential provider debug

### ISSUE THREAD

**Issue by knyatsenko** [tylermenezes/Rfid-Credential-Provider#1]
Hi! Could you give me some advice how to run your credential provider in debug mode under Visual Studio. Thnks.

**Comment by tylermenezes** [comment]
I haven't run this in about 9 years, so I'm not totally sure. Off the top of my head:

- You can register the debug DLL location in the registry
- The CredUILauncher (https://github.com/tylermenezes/Rfid-Credential-Provider/tree/master/Provider/CredUILauncher) should let you test the provider in a window, instead of logging in.

This isn't really supported anymore, though, and I don't think it works with modern versions of Windows.
